# fly.toml app configuration file generated for deribit-tooling on 2024-07-19T20:43:59-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deribit-tooling'
primary_region = 'mia'

[build]

[env]
  APP_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
